### ISSUE TITLE
Baseline on psstdata

### ISSUE THREAD

**Issue by Cross-Caps** [PSST-Challenge/psstdata#1]
Is there a baseline system available?
The link in the documentation is invalid.

**Comment by rcgale** [comment]
Hi,

My apologies for the delayed response. I'll need to investigate my github notification settings.

There's a preliminary ASR baseline available at [https://github.com/PSST-Challenge/psstbaseline](https://github.com/PSST-Challenge/psstbaseline). The baseline for Task B should be available very soon.

Thanks,
Robert
